spring:
  application:
    name: Project6
  cache:
    type: redis

  datasource:
    url: jdbc:postgresql://localhost:5433/Project6
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      port: 6380
      host: localhost

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  file:
    path: logs/spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5

  level:
    root: INFO
    org.springframework: TRACE
